output "vpc_id" {
  description = "The ID of the VPC"
  value       = module.network.vpc_id
}

output "private_subnets" {
  description = "List of IDs of private subnets"
  value       = module.network.private_subnets
}

# output "kubectl_config" {
#   description = "kubectl config as generated by the module."
#   value       = module.k8s.kubeconfig
# }